### ISSUE TITLE
JSONRPC Api doesn't work in dev

### ISSUE THREAD

**Issue by Odianosen25** [SoftEtherVPN/SoftEtherVPN#1075]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce? Yes
* [ ] Are you running the latest version of SoftEtherVPN? Yes

**Latest dev**
**Server and Bridge**
**Linux**
**64 Bit**

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Intel i7 NUC**

### Description

The API doesn't work and keeps giving the following errors when trying to use it
```
 raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Expected behavior:**
It should control the server or bridge

**Actual behavior:**
Gives error and nothing happens

### Steps to reproduce

1. Setup server/bridge
2. Try a simple test api call to it
3. Watch as it refuses to function

**Comment by metalefty** [comment]
It works for me.

This shortest snippet that I tried to test the JSON RPC.

```bash
git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
./configure && make -C tmp
cd ./build
sudo ./vpnserver start

curl -k --basic --user administrator  https://localhost:5555/api/ --data '
{
  "jsonrpc": "2.0",
  "id": "rpc_call_id",
  "method": "GetCaps",
  "params": {}
}'
```

The JSON-RPC returns the following JSON.
```json
{
    "result": {
        "CapsList": [
            {
                "CapsDescrption_utf": "最大 Ethernet パケットサイズ",
                "CapsName_str": "i_max_packet_size",
                "CapsValue_u32": 1600
            },
            {
                "CapsDescrption_utf": "最大仮想 HUB 数",
                "CapsName_str": "i_max_hubs",
                "CapsValue_u32": 100000
            },
            {
                "CapsDescrption_utf": "最大同時接続可能セッション数",
                "CapsName_str": "i_max_sessions",
                "CapsValue_u32": 100000
            },
            {
                "CapsDescrption_utf": "最大作成可能ユーザー数",
                "CapsName_str": "i_max_user_creation",
                "CapsValue_u32": 4294967295
            },
            {
                "CapsDescrption_utf": "最大クライアントセッション数",
                "CapsName_str": "i_max_clients",
                "CapsValue_u32": 4294967295
            },
(snip)
```

**Comment by weidi** [comment]
Have the same issue by trying either with the C# client or already with Invoke-Webrequest in Powershell. It works fine with stable but not with dev.
Tried with 5.01 Build 9672 as precompiled windows binary and my own inside a docker container but both show the same error.

**Comment by shynome** [comment]
when I use the node pkg, I have got the same problem: `A client which is non-SoftEther VPN software has connected to the port.`, but if the admin page `https://127.0.0.1:5555/admin/` is working
what is the diffrence between the html5 ajax client sdk and the node package client sdk ?

**Comment by hoang-rio** [comment]
I still got this issue in version **5.02.5180** using [vpnrpc.ts](https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/developer_tools/vpnserver-jsonrpc-clients/vpnserver-jsonrpc-client-typescript/vpnrpc.ts) nodejs library

**Comment by hoang-rio** [comment]
Have any solution to resolve this issue?

**Comment by shipitsin-ilia** [comment]
I'll have a look

**Comment by shipitsin-ilia** [comment]
@weidi , can you help with you powershell repro steps ?

I wrote simple PowerShell script (it requires PowerShell 6 and above due to `-SkipCertificateCheck` flag. However, it works even with mentioned `5.01 Build 9672`

https://gist.github.com/shipitsin-ilia/5b31c3415187d91947854b2064641b61

**Comment by weidi** [comment]
Issue happens when specifying X-VPNADMIN-HUBNAME and X-VPNADMIN-PASSWORD instead of basic auth like so

```powershell
$ErrorActionPreference = 'Stop'

$body = @"
{
    "jsonrpc": "2.0",
    "id": "rpc_call_id",
    "method": "GetCaps",
    "params": {}
}
"@

$headers = @{
    'Content-Type'='application/json'
    'X-VPNADMIN-HUBNAME'= ""
	'X-VPNADMIN-PASSWORD'= "Administrator"
    }

$r = Invoke-WebRequest -UseBasicParsing -Method 'Post' -Uri 'https://192.168.3.2:444/api/' -Body $body -Headers $headers -SkipCertificateCheck
$r.Content
```



`
2023-01-03 20:19:29.928 On the TCP Listener (Port 443), a Client (IP address 192.168.3.85, Host name "a46a01f2-07a2-42c4-aa6b-e475f3fe82cc.fritz.box", Port number 51708) has connected.
2023-01-03 20:19:29.928 For the client (IP address: 192.168.3.85, host name: "a46a01f2-07a2-42c4-aa6b-e475f3fe82cc.fritz.box", port number: 51708), connection "CID-5" has been created.
2023-01-03 20:19:29.948 SSL communication for connection "CID-5" has been started. The encryption algorithm name is "TLS_AES_256_GCM_SHA384".
2023-01-03 20:19:29.978 Connection "CID-5" terminated by the cause "A client which is non-SoftEther VPN software has connected to the port." (code 5).
2023-01-03 20:19:29.978 Connection "CID-5" has been terminated.
2023-01-03 20:19:29.978 The connection with the client (IP address 192.168.3.85, Port number 51708) has been disconnected.
`

This is mentioned in the Help

```
For JSON-RPC client logins:Instead to HTTP basic
authentication, you can also specify the HTTP header parameters as following.

        X-VPNADMIN-HUBNAME: Empty to login to the VPN Server as the entire
        server administrator, or specify the target Virtual Hub name as the hub
        administrator.
        X-VPNADMIN-PASSWORD: Specify the administrative password.

```

**Comment by hoang-rio** [comment]
I tried modify [vpnrpc.ts](https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/developer_tools/vpnserver-jsonrpc-clients/vpnserver-jsonrpc-client-typescript/vpnrpc.ts) with Authorization header but issue still exist with error

```
return _super.call(this, message) || this;
                      ^

Error: HTTP Error: Error socket hang up
    at new HttpClientException (E:\hoangnd\javascript\vpnrpc.ts\dist\vpnrpc.js:3581:23)
    at ClientRequest.<anonymous> (E:\hoangnd\javascript\vpnrpc.ts\dist\vpnrpc.js:3680:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketOnEnd (node:_http_client:478:9)
    at TLSSocket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by hoang-rio** [comment]
Finally I found the issue is send empty X-VPNADMIN-HUBNAME header. If ignore it when it empty [vpnrpc.ts](https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/developer_tools/vpnserver-jsonrpc-clients/vpnserver-jsonrpc-client-typescript/vpnrpc.ts) will be working fine.

Working constructor:

```typescript
constructor(vpnserver_hostname?: string, vpnserver_port?: number, hubname?: string, password?: string, nodejs_https_client_reject_untrusted_server_cert?: boolean)
    {
        let headers: { [name: string]: string } = {};
        let send_credentials: boolean = false;

        nodejs_https_client_reject_untrusted_server_cert = is_null(nodejs_https_client_reject_untrusted_server_cert) ? false : nodejs_https_client_reject_untrusted_server_cert!;

        if (is_null(vpnserver_hostname))
        {
            this.rpc_url = "/api/";
            send_credentials = true;
        }
        else
        {
            if (is_null(vpnserver_port)) vpnserver_port = 443;
            this.rpc_url = `https://${vpnserver_hostname}:${vpnserver_port}/api/`;

            if (hubname) {
                headers["X-VPNADMIN-HUBNAME"] = hubname!;
            }
            if (password) {
                headers["X-VPNADMIN-PASSWORD"] = password!;
            }
        }

        if (is_null(nodejs_https_client_reject_untrusted_server_cert)) nodejs_https_client_reject_untrusted_server_cert = false;

        this.rpc_client = new JsonRpcClient(this.rpc_url, headers, send_credentials, nodejs_https_client_reject_untrusted_server_cert);
    }
```
