### ISSUE TITLE
SoftEther binary fails TLS negotiation (build from source works)

### ISSUE THREAD

**Issue by MatAtBread** [SoftEtherVPN/SoftEtherVPN#1499]
### Prerequisites

* [ Y ] Can you reproduce?
* [ Y ] Are you running the latest version of SoftEtherVPN?

**SoftEther version: ** v4.38 Build 9760
**Component:** Server
**Operating system:** Linux (Raspbia)
**Architecture:** 64 bit, I think (the CPU is), but the "Product Name" reports as 32 bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** Raspberry Pi 3 Model B Plus Rev 1.3

### Description

For some reason, as mentioned here https://github.com/kittoku/Minimum-VPN-Client-for-SoftEther-VPN/issues/1, the supplied binary for `vpnserver` fails TLS/SSL negotiation with Android clients (notably with the SoftEther protocol, but possibly SSTP as well).

Building the binary from source on the device works in my setup (Raspberry PI 3+, Raspbian 9 [Stretch]) with the same Android clients (Pixel 3a, Android 11 & 12).

Perhaps the version of OpenSSL on your build system needs updating?

**Expected behavior:**
Connection using SoftEther protocol

**Actual behavior:**
Exception on the client:
```
[2021-11-02 18:29:53.003] Connecting has been attempted
[2021-11-02 18:30:02.172] An exception/error has been occurred:
javax.net.ssl.SSLProtocolException: Read error: ssl=0x770d9c2318: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:594 0x772d9a0f78:0x00000001)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.receiveStream(TCPTerminal.kt:99)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.extendStream(TCPTerminal.kt:122)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.ensureSomeFrame(TCPTerminal.kt:262)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.access$ensureSomeFrame(TCPTerminal.kt:29)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal$ensureSomeFrame$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

### Steps to reproduce

1. Install SE from prepared binary (in my case RPi B3+. IDK if this is relevant)
2. Install SoftEther protocol client from Android from https://github.com/kittoku/Minimum-VPN-Client-for-SoftEther-VPN/releases/download/v0.3.1/mvc-0.3.1.apk
3. Turn on logging. Attempt connection. Log looks as above.
4. Build SE from source, ensuring all libraries are up to date (eg `openssl/oldoldstable,now 1.1.0l-1~deb9u4 armhf [installed]`)
5. Attempt connection. TLS exception disappears (tho you'll probably get a different one about DHCP, depending how SE is configured....but it connects).

**Comment by chipitsine** [comment]
sorry, you've opened a bug for SE developer edition (which is versioned 5.X), not v4.38


you are welcome to try 5.X version.
however, troubleshooting is common - see server logs (yes, for v4.X it's same), if that does not help, try tcpdump (it is very helpful in terms of SSL handshakes)

**Comment by MatAtBread** [comment]
Oops..sorry. Does the prebuilt version have a repo? Maybe I'll try v5 to see if it still occurs

**Comment by chipitsine** [comment]
v4.x is for https://github.com/SoftEtherVPN/SoftEtherVPN_Stable
(there's no issue tracker :) )

anyway, we are VERY interested in android app. thanks a lot

**Comment by MatAtBread** [comment]
You're welcome - not my app, I was just trying to get it to work as in Android 12 L2TP/IPsec is deprecated. Only IKEv2 is natively supported. But the author of the Android client https://github.com/kittoku would I'm sure be happy to help.
