### ISSUE TITLE
Certificate authenticate by OpenVPN protocol could crash vpn server.

### ISSUE THREAD

**Issue by galachad** [SoftEtherVPN/SoftEtherVPN#758]
Hi, there!
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server]
**Operating system:** [OpenWRT]
**Architecture:** [Marvell EBU Armada]
**Processor:** [device WRT1200AC]

### Description

Trying to establish a connection using dummy certificate without CN field crashing the server. I do not test this bug on other architecture yet. I'm try to send more information if will be needed.

**Expected behavior:**
Server drop connection.

**Actual behavior:**
Server crash

### Steps to reproduce

1. Generate dummy cert with empty CN//FQDN field.
`openssl req -x509 -sha256 -nodes -newkey rsa:2048 -keyout test.key -out test.cer`
2. Try to establish a connection to the SoftEtherVPN server using dummy certificate.
3. VPN server crash.

@davidebeatrici maybe you can confirm or decline this bug.

**Comment by chipitsine** [comment]
can you please provide an output of

`vpncmd 127.0.0.1:443 /SERVER /CMD:ServerInfoGet`

?

**Comment by galachad** [comment]
Ye,
```
Item                            |Value
--------------------------------+-------------------------------------------------------------
Product Name                    |SoftEther VPN Server Developer Edition (32 bit) (Open Source)
Version                         |Version 5.01 Build 9658   (English)
Build                           |Compiled 2018/09/28 12:41:41 by adam at adam
Host Name                       |Sadam
Server Type                     |Standalone Server
Type of Operating System        |Linux
Product Name of Operating System|Linux
Operating System Vendor         |Unknown Vendor
Operating System Version        |Unknown Linux Version
Type of OS Kernel               |Linux Kernel
Version of OS Kernel            |Linux Kernel
```

**Comment by davidebeatrici** [comment]
Hi,

Thank you very much for reporting the issue!

```c
#0  __wcsnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff75f18c2 in __wcsrtombs (dst=0x7ffff669abc0 "\340\253i\366\377\177", src=src@entry=0x7ffff669ab78, len=<optimized out>, ps=ps@entry=0x7ffff669ab80) at wcsrtombs.c:104
#2  0x00007ffff75872d1 in wcstombs (s=<optimized out>, pwcs=<optimized out>, n=<optimized out>) at wcstombs.c:34
#3  0x0000555555601408 in PackLoginWithOpenVPNCertificate (hubname=0x7fffe4013b98 "DEFAULT", username=0x7fffe4013c98 "", x=0x7fffe401e450)
    at Cedar/Protocol.c:7097
#4  0x0000555555682544 in NewIPC (cedar=0x5555557c7e20, client_name=0x7fffe4013798 "OpenVPN Client", postfix=0x7fffe4013998 "OPENVPN_L3", hubname=0x7fffe4013b98 "DEFAULT", 
    username=0x7fffe4013c98 "", password=0x7fffe4013d98 "", error_code=0x7fffe4014310, client_ip=0x7fffe4013e98, client_port=50042, server_ip=0x7fffe4013eb4, server_port=1194, 
    client_hostname=0x7fffe4013ed0 "52:54:00:3c:28:db", crypt_name=0x7fffe40140d0 "aes-128-cbc", bridge_mode=0, mss=1329, eap_client=0x0, client_certificate=0x7fffe401e450)
    at Cedar/IPC.c:430
#5  0x0000555555682246 in NewIPCByParam (cedar=0x5555557c7e20, param=0x7fffe4013798, error_code=0x7fffe4014310) at Cedar/IPC.c:322
#6  0x0000555555681e60 in IPCAsyncThreadProc (thread=0x7fffe403ea20, param=0x7fffe4013790) at Cedar/IPC.c:215
#7  0x00005555556bba15 in ThreadPoolProc (t=0x7fffac001ec0, param=0x7fffac003230) at Mayaqua/Kernel.c:983
#8  0x00005555557032ac in UnixDefaultThreadProc (param=0x7fffac0037b0) at Mayaqua/Unix.c:1672
#9  0x00007ffff793ff2a in start_thread (arg=0x7ffff669d440) at pthread_create.c:463
#10 0x00007ffff7645edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by galachad** [comment]
Tested it's working correctly right now. Thanks, @davidebeatrici for this fast bugfix.
